--接口平台转换规则·查询模板SQL脚本

insert into pub_query_templet (DESCRIPTION, DEVORG, DR, FIXCONDITION, FIXQUERYTREE, ID, LAYER, METACLASS, MODEL_CODE, MODEL_NAME, NODE_CODE, PARENTID, PK_CORP, PK_ORG, RESID, TS)
values (null, '~', null, null, '<BLOB>', '1001ZZ10000000008CXG', null, null, 'TR010501', '接口平台转换规则查询模板', 'TR010501', '~', '@@@@', '~', null, '2018-04-13 12:03:09');

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, EXT1, EXT2, EXT3, EXT4, EXT5, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_ATTRREFUSED, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MULTICORPREF, IF_MUST, IF_NOTMDCONDITION, IF_ORDER, IF_SUBINCLUDED, IF_SUM, IF_SYSFUNCREFUSED, IF_USED, INSTRUMENTSQL, ISCONDITION, LIMITS, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 0, 1, null, 0, null, null, null, null, null, 'ext_code', '外系统编码', null, '1001ZZ10000000008CXI', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', null, 'Y', 9999, null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '1001ZZ10000000008CXG', null, null, 2, null, null, '2018-04-13 12:01:00', 'N', null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, EXT1, EXT2, EXT3, EXT4, EXT5, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_ATTRREFUSED, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MULTICORPREF, IF_MUST, IF_NOTMDCONDITION, IF_ORDER, IF_SUBINCLUDED, IF_SUM, IF_SYSFUNCREFUSED, IF_USED, INSTRUMENTSQL, ISCONDITION, LIMITS, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 1, 1, null, 0, null, null, null, null, null, 'ext_name', '外系统名称', null, '1001ZZ10000000008CXJ', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', null, 'Y', 9999, null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '1001ZZ10000000008CXG', null, null, 2, null, null, '2018-04-13 12:01:00', 'N', null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, EXT1, EXT2, EXT3, EXT4, EXT5, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_ATTRREFUSED, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MULTICORPREF, IF_MUST, IF_NOTMDCONDITION, IF_ORDER, IF_SUBINCLUDED, IF_SUM, IF_SYSFUNCREFUSED, IF_USED, INSTRUMENTSQL, ISCONDITION, LIMITS, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 2, 1, null, 0, null, null, null, null, null, 'ext_bill_coe', '外系统单据编码', null, '1001ZZ10000000008CXK', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', null, 'Y', 9999, null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '1001ZZ10000000008CXG', null, null, 2, null, null, '2018-04-13 12:01:00', 'N', null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, EXT1, EXT2, EXT3, EXT4, EXT5, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_ATTRREFUSED, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MULTICORPREF, IF_MUST, IF_NOTMDCONDITION, IF_ORDER, IF_SUBINCLUDED, IF_SUM, IF_SYSFUNCREFUSED, IF_USED, INSTRUMENTSQL, ISCONDITION, LIMITS, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('-99', 0, 3, 1, null, 0, null, null, null, null, null, 'ext_bill_name', '外系统单据名称', null, '1001ZZ10000000008CXL', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y', null, 'Y', 9999, null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@相似@', 0, '@@@@', '1001ZZ10000000008CXG', null, null, 2, null, null, '2018-04-13 12:01:00', 'N', null);

insert into pub_query_condition (CONSULT_CODE, DATA_TYPE, DISP_SEQUENCE, DISP_TYPE, DISP_VALUE, DR, EXT1, EXT2, EXT3, EXT4, EXT5, FIELD_CODE, FIELD_NAME, GUIDELINE, ID, IF_ATTRREFUSED, IF_AUTOCHECK, IF_DATAPOWER, IF_DEFAULT, IF_DESC, IF_GROUP, IF_IMMOBILITY, IF_MULTICORPREF, IF_MUST, IF_NOTMDCONDITION, IF_ORDER, IF_SUBINCLUDED, IF_SUM, IF_SYSFUNCREFUSED, IF_USED, INSTRUMENTSQL, ISCONDITION, LIMITS, MAX_LENGTH, OPERA_CODE, OPERA_NAME, ORDER_SEQUENCE, PK_CORP, PK_TEMPLET, PRERESTRICT, RESID, RETURN_TYPE, TABLE_CODE, TABLE_NAME, TS, USERDEFFLAG, VALUE)
values ('影响因素单据类型', 5, 4, 1, null, null, null, null, null, null, null, 'nc_bill_type', 'NC系统单据类型', null, '1001ZZ10000000008CXM', 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', null, 'Y', 9999, null, '=@>@>=@<@<=@like@', '等于@大于@大于等于@小于@小于等于@包含@', 0, '@@@@', '1001ZZ10000000008CXG', null, null, 2, null, null, '2018-04-13 12:03:09', 'N', null);

--模块信息
insert into dap_dapsystem (APPSCOPE, DEF1, DEF2, DEF3, DEVMODULE, DR, ISACCOUNT, ISITEM, ISNCINNERMODULE, ISRELATEDEV, MODULEID, NODEORDER, ORGTYPECODE, PARENTCODE, PRODUCTSCOPE, RESID, SUPPORTCLOSEACCBOOK, SYSTYPECODE, SYSTYPENAME, TS)
values (1, null, null, null, 'uapeai', 0, 'N', 'N', 'Y', null, '12H8', null, 'GLOBLE00000000000000', '12', null, null, 'N', '12H8', '接口平台', '2018-04-18 00:12:04');

--功能注册
insert into sm_funcregister (CFUNID, CLASS_NAME, DR, FUN_DESC, FUN_NAME, FUN_PROPERTY, FUNCODE, FUNTYPE, HELP_NAME, ISBUTTONPOWER, ISCAUSERUSABLE, ISENABLE, ISFUNCTYPE, MDID, ORGTYPECODE, OWN_MODULE, PARENT_ID, PK_GROUP, TS)
values ('1001ZZ10000000008QTL', 'nc.ui.apiplat.changeui.BillMappingUI', 0, null, '接口转换规则', 0, '12H80001', 0, null, null, 'N', 'Y', 'N', '~', 'GROUPORGTYPE00000000', '12H8', null, '~', '2018-04-18 00:13:23');

--菜单注册
insert into sm_menuitemreg (DR, FUNCODE, ICONPATH, ISMENUTYPE, MENUDES, MENUITEMCODE, MENUITEMNAME, NODEORDER, PK_MENU, PK_MENUITEM, RESID, TS)
values (0, '12H80001', null, 'N', null, '12H801', '数据转换规则', null, '1004ZZ10000000000FFL', '1001ZZ10000000008QTO', 'D12H801', '2018-04-18 00:15:16');

insert into sm_menuitemreg (DR, FUNCODE, ICONPATH, ISMENUTYPE, MENUDES, MENUITEMCODE, MENUITEMNAME, NODEORDER, PK_MENU, PK_MENUITEM, RESID, TS)
values (0, null, null, 'Y', null, '12H8', '接口平台', null, '1004ZZ10000000000FFL', '1001ZZ10000000008QTN', 'D1201', '2018-04-18 00:14:16');

commit;